CODEOWNERS
build.gradle
stack-orchestration/README.md
stack-orchestration/configuration/build/build-rp-stub-pipeline/parameters.json
stack-orchestration/configuration/build/tags.json
stack-orchestration/configuration/int/tags.json
stack-orchestration/configuration/prod/tags.json
stack-orchestration/configuration/stage/tags.json

- Update sonar references
- update codeowners
- update readme reference
- update tags and parameters for secure pipelines
Make the updates necessary for the new org

ATO-156: Update codebase for repo migration:

---

Dockerfile
README.MD
build.gradle
docker-compose.yml
src/main/java/uk/gov/di/OidcRp.java
src/main/java/uk/gov/di/config/RelyingPartyConfig.java
template.yaml

ATO-NONE: move cloudformation to new repo

---

.github/workflows/sonar-analysis-on-merge.yml
src/main/java/uk/gov/di/config/RelyingPartyConfig.java

We currently don't lint java on merge - this adds that

ATO-156: Add linting of java to merge

---

.github/workflows/on-merge.yml
.github/workflows/pull-request.yml
.github/workflows/run-checks.yml

Validates sam on opening pull request and merge
We now have sam templates and want to make sure they are valid

ATO-156: Add sam validation to ci

---

.github/workflows/on-merge.yml

Adding deployment to ECR on merge
So we can deploy infrastructure to ECR

ATO-157: Add deployment to pipeline

---

stack-orchestration/configuration/build/build-rp-stub-pipeline/parameters.json
stack-orchestration/configuration/int/int-rp-stub-pipeline/parameters.json
stack-orchestration/configuration/prod/prod-rp-stub-pipeline/parameters.json
stack-orchestration/configuration/stage/stage-rp-stub-pipeline/parameters.json

ATO-157: Fix lambda signing config

---

template.yaml

Remove ip restrictions for build stub

ATO-154: Remove ip restricting for build

---

.github/workflows/run-checks.yml
build.gradle
src/test/java/uk/gov/di/handlers/HomeHandlerTest.java

ATO-NONE: Add testing to stub

---

stack-orchestration/configuration/build/build-rp-stub-pipeline/parameters.json
stack-orchestration/configuration/int/int-rp-stub-pipeline/parameters.json
stack-orchestration/configuration/prod/prod-rp-stub-pipeline/parameters.json
stack-orchestration/configuration/stage/stage-rp-stub-pipeline/parameters.json
template.yaml

Reverts govuk-one-login/relying-party-stub#24

Revert "ATO-157: Remove lambda signing config"

---

.github/workflows/run-checks-and-deploy.yml

- fix secret name
- add option for workflow dispatch
- add dependency on checks for deployment

ATO-157: Fix deployment

---

.github/workflows/run-checks-and-deploy.yml

ATO-157: Fix template name

---

template.yaml

Add client ids and secrets to template for stub
So we can access one login from the stubs

ATO-159/setup stubs as relying parties

---

template.yaml

Update urls in template
Have updated since merging

ATO-154: Update urls with incorrect suffix

---

stack-orchestration/configuration/build/build-rp-stub-pipeline/parameters.json
stack-orchestration/configuration/int/int-rp-stub-pipeline/parameters.json
stack-orchestration/configuration/prod/prod-rp-stub-pipeline/parameters.json

Update deployment parameters
So deployments and promotions are in correct order

ATO-157: Update deployment params so deployment is build->stage->int,prod

---

template.yaml

Update prod client ids in template
the client registry entries updated which meant the id's did not match the table entries

ATO-159: Update production client ids in template

---

template.yaml

ATO-344: Fix secret reference for perf test client

---

stack-orchestration/manual-stacks/dns-zones/README.md
stack-orchestration/manual-stacks/dns-zones/template.yaml
template.yaml

Create DNS entries and corresponding certificates for the new stubs. Mostly written by @isaac-GDS 
Migrated from https://github.com/alphagov/di-auth-stub-relying-party/pull/277

ATO-204/205: setup manual stacks dns

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy.yml
.github/workflows/run-checks-and-deploy.yml

Move needs line to where deploy action is called
Deployment is currently broken

ATO-350: Move needs line to where deploy is called

---

.github/workflows/deploy-dev.yml

ATO-350: Change the secret used for deployment

---

.gitignore

ATO-NONE: Add aws sam files to gitignore

---

template.yaml

Add test client for build
To have a client for acceptance tests

Ato 383/add test client for build

---

.github/workflows/run-checks.yml
template.yaml

SAM template is currently broken, fix the conditions, and increase the sensitivity of the sam linter to catch future problems
The build is currently failing

ATO-383 Fix sam template

---

.env.template
README.MD

Update the documentation for the stub
To make it easier to use and develop on

ATO-160: Update stub documentation

---

template.yaml

ATO-383: Add acceptance test client id

---

template.yaml

Scale up the staging perf test stub
To support an upcoming load test

BAU: scale up perf stub for load testing

---

template.yaml

BAU: Correct acceptance test url

---

stack-orchestration/manual-stacks/dns-zones/README.md
stack-orchestration/manual-stacks/dns-zones/deploy_dns.sh
stack-orchestration/manual-stacks/dns-zones/template.yaml

Add dns for acceptance tests
This has now been deployed

ATO-383: Add dns for acceptance tests

---

build.gradle
src/main/java/uk/gov/di/OidcRp.java
src/main/java/uk/gov/di/handlers/ExceptionHandler.java
src/main/java/uk/gov/di/handlers/InternalServerErrorHandler.java
src/main/resources/log4j2.xml

Implements log4j and tidies up exception handling
Log4j allows us to make our error messages cleaner. I've also updated our exception handling, because it wasn't catching runtime exceptions in the stub.

ATO-399/update logging config

---

src/main/resources/templates/userinfo.mustache

ATO-362: Update template to include correct wallet_subject_id values

---

src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
src/main/resources/templates/userinfo.mustache

Show full access token and user info response
Makes testing and debugging easier

BAU: Show full access token and user info response

---

template.yaml

ATO-NONE: fix build client ids

---

template.yaml

Set up log subscription filters
So logs pipe to splunk

ATO-217: Set up subscription filters to pipe logs to splunk

---

build.gradle

Update log4j. Create variable to keep versions in sync

BAU: Update log4j

---

template.yaml

Fix dev client ids
Deployed a change to dev client registry that updated client ids

ATO-NONE: Fix dev client ids

---

template.yaml
testtemplate.yaml

fixing small typo in Scaling policy Build failed in Build ENV , not sure why this was not picked up in CF validation :(

Auth-2681 create scaling for staging rp stub

---

template.yaml

Update docappDefaultClientId to fix stub.

BAU: Update docappDefaultClientId

---

.github/workflows/deploy.yml

updating devplatform-upload-action to v3.8.1

updating devplatform-upload-action to v3.8.1

---

authorizer/authorizer.js

BAU: add ITHC IPs to allowlist

---

.github/workflows/deploy.yml

Reverts govuk-one-login/relying-party-stub#175

Revert "Bump govuk-one-login/devplatform-upload-action from 3.8.1 to 3.9"

---

authorizer/authorizer.js

Allow Auth dev account access to Dev RP stub
We are creating acceptance test to run in AUTH dev account on Dev RP stub so we need AWS codebuild London region public IP whit listed

Allow Auth dev account access to Dev RP stub

---

src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
src/main/resources/templates/userinfo.mustache

Show journey ID on the user info page
Requested by IPV to assist in correlating logs

BAU: Show journey ID in user info for log tracing

---

src/main/java/uk/gov/di/OidcRp.java
src/main/java/uk/gov/di/config/RPConfig.java
src/main/java/uk/gov/di/handlers/JwkHandler.java
src/main/java/uk/gov/di/utils/Oidc.java
src/test/java/uk/gov/di/handlers/JwkHandlerTest.java

Also add key use to JWKS
https://github.com/govuk-one-login/authentication-api/pull/4882

ATO-912: Add kid to JWKS and include in signed JWT header

---

authorizer/authorizer.js

Allowlist IPs to allow pentesters to access stubs

ATO-923: Allowlist IPs for programme pentest

---

src/main/resources/templates/home.mustache

See https://github.com/govuk-one-login/authentication-api/pull/5055

ATO-986: Enable P1

---

src/main/resources/templates/userinfo.mustache

BAU: Fix id for user info response element

---

src/main/java/uk/gov/di/utils/CoreIdentityValidator.java

If the did host has a port, we should get that port

BAU: Fix did controller check

---

src/main/java/uk/gov/di/utils/CoreIdentityValidator.java

BAU: Add percent decoding of the did controller port

---

build.gradle

BAU: Pin netty common due to CVE-2024-47535

---

authorizer/authorizer.js
template.yaml

BAU: temp turn off IP restriction

---

.github/workflows/deploy.yml
.github/workflows/gradle-graph.yml
.github/workflows/require-pinned-github-actions.yml
.github/workflows/run-checks.yml

BAU: require pinned github actions

---

src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
src/main/java/uk/gov/di/utils/Oidc.java
src/main/resources/templates/home.mustache
src/test/java/uk/gov/di/utils/OidcTest.java

Add channel claim to RP stub, with web as default

ATO-1695: add channel to RP stub

---

authorizer/authorizer.js

Adds the new DSIT VPN IP to the authorizer

ATO-1723: Allow new DSIT VPN to access the stub
