govuk-one-login/relying-party-stub

- stack-orchestration/configuration/build/build-rp-stub-pipeline/parameters.json
- stack-orchestration/configuration/int/int-rp-stub-pipeline/parameters.json
- stack-orchestration/configuration/prod/prod-rp-stub-pipeline/parameters.json
- stack-orchestration/configuration/stage/stage-rp-stub-pipeline/parameters.json
- template.yaml
Remove lambda signing config
We can't deploy signed lambda and ecr at the same time
> ATO-157: Remove lambda signing config

- .github/workflows/on-merge.yml
Add manual push to ecr and signing of lambdas to deployment
Dev platform have confirmed you cannot sign lambdas in the upload to ecr action: https://gds.slack.com/archives/C02U78Y5J3H/p1706700210012519?thread_ts=1706697999.762499&cid=C02U78Y5J3H
> ATO-157: Add manual push to ecr and signing to deployment

- authorizer/authorizer.js
- template.yaml
Remove lambda authorizer code out of inline to separate file
secure pipelines depends on the codeuri template property which inline code doesn't have
> ATO-157: Move lambda authorizer out of inline

- authorizer/authorizer.js
Add IP addresses in lambda authorizer for performance test requests
So performance testers can use the stub for perf tests on the service
> ATO-154: Add IP addresses for performance test requests

- template.yaml
Update resource tags to new org
They were still referencing the alphagov repo
> ATO-154: Update tags to new org

- stack-orchestration/configuration/build/build-rp-stub-pipeline/parameters.json
Add build promotion allowed account
Needed for deployment to succeed
> ATO-158: Add build promotion allowed accounts

- template.yaml
Only export the perf test API ID in staging
It does not exist in other environments
> ATO-204: Only export perf test in staging

- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
- src/main/java/uk/gov/di/handlers/HomeHandler.java
- src/main/java/uk/gov/di/handlers/SignOutHandler.java
Set ID token in cookie instead of session
Session is stored in memory, which is not shared across multiple servers. Ths does not work for performance testing, which has 6 instances
> BAU: Set ID token in cookie instead of session

- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/resources/templates/home.mustache
- src/main/resources/templates/userinfo.mustache
- Add checkbox to select wallet subject ID scope
- Display wallet subject ID on end userInfo page
To be able to select the wallet subject ID scope
https://github.com/govuk-one-login/authentication-api/pull/4003
> ATO-362: Add wallet subject ID scope

- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
Update wallet-subject-id value and remove mention of claim
New format as a scope and removing "claim" should make it clearer that it isn't one of the valid claims
https://github.com/govuk-one-login/relying-party-stub/pull/83
https://github.com/govuk-one-login/authentication-api/pull/4046
> ATO-362: Update wallet-subject-id as now a scope not a claim

- src/main/resources/templates/home.mustache
Change 'auth' to 'authentication'
For consistency on the landing page
> ATO-NONE: Tidy up home page text

- template.yaml
Create configuration secret for #99 
To roll out #99 without downtime
> ATO-441: create configuration secrets

- template.yaml
Deafult client ids have change because of introducing for_each rather than count in the terraform setup
> ATO-404: Update default client ids

- template.yaml
AUTH-2681 Adding Scaling policy for staging test client RP Stub
We have a Perf Test which use staging test client RP stub , recent test shown that nos desired task are not enough to support the high volume test so adding a scaling policy to ECS task running Stubs to scale when CPU Utilisation is more than 50% or No of request Per Target is >2000
Also Adjusting the Target Health check value for test service  Heath check interval to 10 sec with 2 consecutive health check successes , so the target get ready and gets in service within 20 sec
> AUTH-2681 Adding Scaling policy for staging test client RP Stub

- template.yaml
lowering the desired Count for Staging RP
Performance test are now running from performance RP created in Performance test Account so we don't need Staging RP to run 4 task  so lowering the count from 4 to 1 task however the scaling is in place if Traffic is on RP it will scale
> lowering the desired Count for Staging RP

- template.yaml
* RetentionInDays changed to 30 in template.yaml
See https://govukverify.atlassian.net/browse/SW-295 and associated epic https://govukverify.atlassian.net/browse/SW-241
Currently any log retention that is set under 30 days will be set to 30 by a Lambda attached to the LZA Lambda run
> log retention settings have been updated to 30 days

- build.gradle
- config.json.template
- src/main/java/uk/gov/di/config/RPConfig.java
- src/main/java/uk/gov/di/utils/CoreIdentityValidator.java
- src/test/java/uk/gov/di/utils/CoreIdentityValidatorTest.java
SPOT are publishing their signing key(s) on a new endpoint in DID format. This change is to:
- Replace the public key in configuration with a URL to fetch keys from
- Update the Core Identity Validator to fetch the correct key and validate the signature using it
- Perform the validation suggested in the upcoming tech docs change (https://github.com/govuk-one-login/tech-docs/pull/200/files)
- Cache the fetched key indefinitely
In future, we should read and respect the cache control headers on the DID endpoint.
~~We have added a new dependency for this which is not published to maven central. It is limited to only the required packages, but if they add new dependencies we may need to allow more in the future.~~ This has been included in artifactory: …
> BAU: Update the identity signing validation logic to use the DID for SPOT signing keys

- .github/workflows/dependency-graph.yml
Use an action to generate and submit dependencies to populate GitHub's dependency graph
> BAU: Upload gradle dependencies

- build.gradle
- src/main/java/uk/gov/di/OidcRp.java
- src/main/java/uk/gov/di/config/Configuration.java
- src/main/java/uk/gov/di/config/RPConfig.java
- src/main/java/uk/gov/di/handlers/JwkHandler.java
- src/main/java/uk/gov/di/utils/PrivateKeyReader.java
- src/test/java/uk/gov/di/handlers/JwkHandlerTest.java
- src/test/java/uk/gov/di/helpers/keyHelper.java
- src/test/java/uk/gov/di/utils/PrivateKeyReaderTest.java
- Adds new routes for each stub RP in the format `/:clientId/.well-known/jwks.json` publishing their public key.
- These routes dynamically generate for each RP provided in the config
- Adds a new JWK handler and relevant dependencies 
- This allows us to test fetching an RP public key from a JWKs endpoint. 
- Code review commit-by-commit
> ATO-692: JWKs endpoints for RP stub

- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/resources/templates/home.mustache
Add account management to stub scopes
By adding the AM to the list of scopes, we can obtain a bearer token (at the end of a journey which logs the user in) which contains "am" in the scopes claim. This is needed for acceptance tests for account management.
> BAU: add account management to stub scopes

- src/main/java/uk/gov/di/utils/CoreIdentityValidator.java
- src/test/java/uk/gov/di/utils/CoreIdentityValidatorTest.java
- We should match the entire `kid` to the `id` of the verification method in the DID document.
The format of the DID document has recently changed, see PR https://github.com/govuk-one-login/tech-docs/pull/238
https://github.com/govuk-one-login/tech-docs/pull/238
> BAU: Alter kid to DID key ID matching

- src/main/resources/templates/userinfo.mustache
Add unique id to user info access token
The same id is used for different elements with different scopes. This adds an unique id for the access (bearer) token
> BAU: add unique id to user info access token

- build.gradle
This will also fix the security advisory
> BAU: Rewrite dependency constraint to ensure jetty stays on latest patch

- src/main/java/uk/gov/di/utils/CoreIdentityValidator.java
- src/test/java/uk/gov/di/helpers/TestClock.java
- src/test/java/uk/gov/di/utils/CoreIdentityValidatorTest.java
Limit the time core identity signing keys are cached for to respect the max-age parameter in the cache control header
Without cache expiry, key revocation does not work. This is not a particular issue for the stub, but this code is being used as reference by RPs.
> BAU: Add expiry to DID caching

- CODEOWNERS
Orchestration own this repo. So in the spirit of the auth/orch split, removing auth as an owner of this repo.
> BAU: Remove auth team as CODEOWNERS

- src/main/java/uk/gov/di/utils/Oidc.java
- src/test/java/uk/gov/di/utils/OidcTest.java
Fixes the formatting of claims in the request object so that they are specified as `userinfo` claims and not just top level JSON keys
As part of other work[1], we're adding validation to the claims included in request objects. This requires us to put the claims nested under the 'userinfo' property which the code is not currently doing. This corrects that by attatching the claims as userinfo claims when making a request object authorize JAR
[1]- https://github.com/govuk-one-login/authentication-api/pull/5721
> ATO-1329: Fix claim format in request object

- build.gradle
> BAU: Pin jetty-http due to CVE-2024-6763

- build.gradle
Reverts govuk-one-login/relying-party-stub#418
This PR breaks the build. The vulnerability is not relevant to jetty-http v10, as discussed in this thread: https://github.com/jetty/jetty.project/pull/12012
Also, since we don't directly use the dependency and instead use it through another jetty package, the thread confirms that we are not subject to the vulnerability
> Revert "BAU: Pin jetty-http due to CVE-2024-6763"

- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/resources/templates/home.mustache
- src/main/resources/templates/userinfo.mustache
- template.yaml
- Removes the `SocialSecurityRecord` claim from the stub
- We stopped supporting this claim a while ago and are now removing it
> ATO-1411: Remove social security claim from stub

- src/main/java/uk/gov/di/handlers/AuthCallbackHandler.java
- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/java/uk/gov/di/utils/Oidc.java
- src/main/resources/templates/home.mustache
- src/test/java/uk/gov/di/utils/OidcTest.java
- Added PKCE toggle to UI
- New code verifier initialised each time we hit the `authorize` handler (to ensure this value is short-lived (only used once))
- Updated `authorize` request builders to support PKCE if a code verifier is supplied
- `Authorize callback` handler passes the code verifier (if defined) to initialise the code grant
- Wipes the cookie (if defined) after reading to allow the PKCE off/"no" case to be immediately tested
We are adding PKCE support to `authentication-api`, the RP stub needs to be updated to reflect this.
UI changes (new PKCE toggle, fixed the overflow for the grid item to the left of the PKCE grid item):
> ATO-1464: add PKCE support

- src/main/resources/templates/signedout.mustache
Make it easier to start a new journey after signing out
> BAU: Add start again button to signed out page

- src/main/java/uk/gov/di/handlers/AuthorizeHandler.java
- src/main/java/uk/gov/di/utils/Oidc.java
- src/main/resources/templates/home.mustache
- src/test/java/uk/gov/di/utils/OidcTest.java
I didn't like pushing it under another item so it's on it's own row
As part of the login_hint work, need to be able to add login_hint (email). It won't be passed on if it comes from query params.
For now ignore second commit as that will be removed, it's only been added for testing
https://github.com/govuk-one-login/authentication-api/pull/6512
> ATO-1627: add login_hint

- .github/workflows/deploy.yml
We recently merged in a dependabot PR to update the `cosign-installer` dependency. This requires us to use a cosign version of at least v2.0.0. We are currently requesting v1.9.0 so this GHA fails (see https://github.com/govuk-one-login/relying-party-stub/actions/runs/16751577799/job/47423081611)
This PR requests the latest cosign version (v2.5.3). I deployed and tested this in dev and the deployment was successful
> BAU: Use valid cosign version

- build.gradle
Two dependabot issues with current version of netty-codec
https://github.com/govuk-one-login/relying-party-stub/security/dependabot/11
https://github.com/govuk-one-login/relying-party-stub/security/dependabot/12
> ATO-1970: Bump netty-codec-http2 to 4.1.125+
